# dnsmasq config for iPXE boot
port=0
interface=lo
bind-interfaces
dhcp-range=10.0.2.100,10.0.2.200,12h
dhcp-boot=boot.ipxe,,10.0.2.2
enable-tftp
tftp-root=/home/paalgyula/wspace/poc/pivirt-linux/tftpboot
log-dhcp
